package demo.spring.model;
// Generated Mar 23, 2015 2:26:48 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String firstName;
     private Integer lastName;
     private String loginId;
     private String password;
    public User() {
    }

	
    public User(int id, String firstName) {
        this.id = id;
        this.firstName = firstName;
    }
    public User(int id, String firstName, Integer lastName, String loginId, String password) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.loginId = loginId;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public Integer getLastName() {
        return this.lastName;
    }
    
    public void setLastName(Integer lastName) {
        this.lastName = lastName;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }




}


